const APP_NAME = "AutoWorkshop MMS";
const API_BASE_URL = "/api";
const DEFAULT_PAGE_SIZE = 10;

const USER_ROLES = {
    ADMIN: "ADMIN",
    CASHIER: "CASHIER",
};

const TRANSACTION_STATUSES = {
    PENDING: "PENDING",
    UNPAID: "UNPAID",
    PARTIAL: "PARTIAL",
    PAID: "PAID",
    CANCELLED: "CANCELLED",
};

const PACKAGE_ITEM_TYPES = {
    PRODUCT: "PRODUCT",
    SERVICE: "SERVICE",
    PACKAGE: "PACKAGE",
    EXTERNAL: "EXTERNAL",
};

const EXPENSE_CATEGORIES = {
    SALARY: "SALARY",
    UTILITIES: "UTILITIES",
    PURCHASING: "PURCHASING",
    OTHER: "OTHER",
};

export {
    APP_NAME,
    API_BASE_URL,
    DEFAULT_PAGE_SIZE,
    USER_ROLES,
    TRANSACTION_STATUSES,
    PACKAGE_ITEM_TYPES,
    EXPENSE_CATEGORIES,
};